services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://todo_user:todo_pass@db:5432/todo_db
    command: uv run alembic -x dburl=postgresql://todo_user:todo_pass@localhost:5432/todo_db upgrade head

  tests:
    build: ./backend
    depends_on:
      - db
      - migrations
    environment:
      DATABASE_URL: postgresql://todo_user:todo_pass@db:5432/todo_db
    command: uv pytest backend/api/tests/


  backend:
      build: .
      container_name: todo-backend
      depends_on:
        - db
        - migrations
        - tests
      environment:
        DATABASE_URL: postgresql://todo_user:todo_pass@db:5432/todo_db
      ports:
        - "8000:8000"
      command: uv run uvicorn backend.api.app:app --host 0.0.0.0 --port 8000 --workers 4

volumes:
  postgres_data: